# Generated by Django 4.0.10 on 2023-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.IntegerField(db_column='UserType')),
                ('signupdatetime', models.DateTimeField(blank=True, db_column='SignUpDateTime', null=True)),
                ('mobileauthenticationenabled', models.IntegerField(db_column='MobileAuthenticationEnabled')),
                ('emailauthenticationenabled', models.IntegerField(db_column='EmailAuthenticationEnabled')),
                ('mobilephone', models.CharField(blank=True, db_column='MobilePhone', max_length=20, null=True)),
                ('profilepiclink', models.CharField(blank=True, db_column='ProfilePicLink', max_length=128, null=True)),
                ('birthdate', models.DateTimeField(db_column='BirthDate')),
            ],
            options={
                'db_table': 'userseller',
                'managed': False,
            },
        ),
    ]
