# Generated by Django 4.0.10 on 2023-02-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nrmlserller_delete_userseller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nrmlserller',
            table='nrmlseller',
        ),
    ]
