# Generated by Django 4.0.10 on 2023-02-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdata_is_emp_userdata_is_normal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
